services:
  - type: web
    name: social-manager-ai-backend
    rootDir: backend
    runtime: python:3.11
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        value: "8088"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: TWILIO_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: SOCIAL_MANAGER_DB_URL
        value: sqlite:///./social_manager.db
      - key: CORS_ORIGINS
        value: '["https://social-community-manager.vercel.app", "https://social-community-manager-bfpz.onrender.com"]'

