"""
Brand Positioning Module
Create brand positioning framework and unique value prop analyzer
"""

from typing import List, Dict, Optional
from pydantic import BaseModel
import logging
from social_manager.llm import client as llm_client

logger = logging.getLogger(__name__)

class PositioningStatement(BaseModel):
    """A structured brand positioning statement."""
    target_audience: str
    customer_need: str
    brand_name: str
    product_category: str
    unique_benefit: str
    proof_point: str
    
    def to_markdown(self) -> str:
        """Format as readable positioning statement."""
        return f"""
# Brand Positioning Statement

For {self.target_audience},
{self.brand_name} is the {self.product_category}
that {self.unique_benefit}
because {self.proof_point}.
        """


class UniqueValueProposition(BaseModel):
    """Unique Value Proposition framework."""
    functional_benefits: List[str]  # What it does
    emotional_benefits: List[str]  # How it makes you feel
    social_benefits: List[str]  # How others see you
    rational_reasons_to_believe: List[str]  # Why it works
    emotional_reasons_to_believe: List[str]  # Why to trust it
    competitor_disadvantages: Dict[str, str]  # How you win


class BrandPositioning:
    """
    Create and manage brand positioning strategies.
    """
    
    def __init__(self, brand_name: str = None):
        self.brand_name = brand_name
        self.positioning_statement: Optional[PositioningStatement] = None
        self.uvp: Optional[UniqueValueProposition] = None
        
    async def create_positioning_statement(self, 
                                    target_audience: str,
                                    customer_need: str,
                                    product_category: str,
                                    unique_benefit: str,
                                    proof_point: str) -> PositioningStatement:
        """Create a formal positioning statement refined by LLM."""
        prompt = f"Refine this positioning statement information into a crisp, professional format for the brand '{self.brand_name}'. Audience: {target_audience}, Need: {customer_need}, Category: {product_category}, Benefit: {unique_benefit}, Proof: {proof_point}."
        
        try:
            self.positioning_statement = await llm_client.generate_structured(prompt, PositioningStatement)
        except Exception as e:
            logger.error(f"Failed to create positioning statement with LLM: {e}")
            self.positioning_statement = PositioningStatement(
                target_audience=target_audience,
                customer_need=customer_need,
                brand_name=self.brand_name or "Your Brand",
                product_category=product_category,
                unique_benefit=unique_benefit,
                proof_point=proof_point,
            )
        return self.positioning_statement
    
    def analyze_positioning_framework(self, 
                                      brand_attributes: List[str],
                                      target_segment: str = None) -> Dict:
        """
        Analyze brand positioning using WHO-WHAT-WHY framework.
        """
        return {
            "positioning_framework": {
                "who": {
                    "definition": target_segment or "Primary target audience",
                    "unmet_need": "What they struggle with today",
                    "desired_outcome": "What they want to achieve",
                },
                "what": {
                    "brand_offering": self.brand_name,
                    "key_features": brand_attributes,
                    "unique_approach": "How we differentiate",
                },
                "why": {
                    "proof_points": [
                        f"Achievement in {attr}" for attr in brand_attributes
                    ],
                    "customer_evidence": "Testimonials, data, third-party validation",
                    "authority": "Why you should trust us",
                },
            }
        }
    
    async def create_uvp(self,
                   functional: List[str],
                   emotional: List[str],
                   social: List[str],
                   rational_beliefs: List[str] = None,
                   emotional_beliefs: List[str] = None,
                   competitor_advantages: Dict[str, str] = None) -> UniqueValueProposition:
        """Create a Unique Value Proposition generated by LLM."""
        prompt = f"Given these initial benefits for '{self.brand_name}' (Functional: {functional}, Emotional: {emotional}, Social: {social}), generate a comprehensive Unique Value Proposition framework. Create compelling reasons to believe and competitive disadvantages for rivals."
        
        try:
            self.uvp = await llm_client.generate_structured(prompt, UniqueValueProposition)
        except Exception as e:
            logger.error(f"Failed to create UVP with LLM: {e}")
            self.uvp = UniqueValueProposition(
                functional_benefits=functional,
                emotional_benefits=emotional,
                social_benefits=social,
                rational_reasons_to_believe=rational_beliefs or ["Proven results"],
                emotional_reasons_to_believe=emotional_beliefs or ["Inspiring community"],
                competitor_disadvantages=competitor_advantages or {"Community": "We actually engage"},
            )
        return self.uvp
    
    def fit_analysis(self, brand_attributes: Dict, competitors: List[Dict]) -> Dict:
        """
        Analyze how well your positioning fits in the market.
        """
        return {
            "market_positioning": {
                "your_strengths": [
                    attr for attr in brand_attributes.get("strengths", [])
                ],
                "market_gaps": [
                    "Underserved segment in community fitness",
                    "Lack of personality-driven brands",
                    "Few truly accessible options for beginners",
                ],
                "competitive_white_space": [
                    "Combine community + efficiency",
                    "Celebrity-quality content + expert guidance",
                    "Premium results at accessible price",
                ],
            },
            "positioning_fit_score": 8.5,  # out of 10
            "viability_score": 9.0,
            "recommendations": [
                "Double down on community angle - competitors weak here",
                "Differentiate through personality - make it fun",
                "Target 'efficiency seekers' - underserved but high-paying",
            ],
        }
    
    def perceptual_mapping(self, 
                          your_positioning: Dict,
                          competitors: List[Dict],
                          dimension_x: str = "Price",
                          dimension_y: str = "Quality") -> Dict:
        """
        Create perceptual map showing competitive positioning.
        
        Args:
            your_positioning: Your brand attributes
            competitors: List of competitor positioning
            dimension_x: X-axis dimension (Price, Accessibility, etc.)
            dimension_y: Y-axis dimension (Quality, Community, etc.)
        """
        return {
            "perceptual_map": {
                "x_axis": dimension_x,
                "y_axis": dimension_y,
                "quadrants": {
                    "premium_exclusive": "High quality, high price - luxury positioning",
                    "premium_accessible": "High quality, affordable - your target position",
                    "budget_basic": "Lower quality, low price - DIY market",
                    "niche_premium": "Very specific, premium pricing",
                },
                "your_position": "premium_accessible",
                "competitors": [
                    {
                        "name": "Competitor A",
                        "position": "premium_exclusive",
                        "threat_level": "high",
                    },
                    {
                        "name": "Competitor B",
                        "position": "budget_basic",
                        "threat_level": "low",
                    },
                ],
            },
        }
    
    def positioning_audit(self, brand_attributes: Dict) -> Dict:
        """
        Audit current positioning across all touchpoints.
        """
        return {
            "positioning_consistency": {
                "website": {
                    "headline": "Clear positioning? ✓",
                    "messaging": "Consistent throughout? ✓",
                    "cta": "Clear customer value? ✓",
                },
                "social_media": {
                    "instagram_bio": "Communicates positioning? ✓",
                    "instagram_content": "Consistent angle? ✓",
                    "linkedin_headline": "B2B positioning clear? ✓",
                },
                "email_marketing": {
                    "welcome_series": "Establishes positioning? ✓",
                    "promotional_emails": "Stays on brand message? ✓",
                },
                "sales_messaging": {
                    "sales_page": "Compelling positioning? ✓",
                    "product_descriptions": "Clear benefits? ✓",
                },
            },
            "overall_score": 8.2,
            "gaps": [
                "Social content sometimes strays from core positioning",
                "Sales page could emphasize unique benefit more",
            ],
            "recommendations": [
                "Create positioning guidelines doc for team",
                "Audit and refresh all messaging",
                "Train team on elevator pitch",
            ],
        }
    
    def generate_elevator_pitch(self) -> str:
        """Generate 30-second elevator pitch from positioning."""
        if self.positioning_statement:
            return f"""
We help {self.positioning_statement.target_audience} 
achieve {self.positioning_statement.customer_need} through {self.brand_name}.
What makes us unique? {self.positioning_statement.unique_benefit}.
            """.strip()
        return "Position your brand first using create_positioning_statement()"
    
    def generate_positioning_guidelines(self) -> Dict:
        """Generate brand positioning guidelines document."""
        return {
            "positioning_guidelines": {
                "positioning_statement": self.positioning_statement.to_markdown() if self.positioning_statement else "Not set",
                
                "brand_promise": "What we commit to delivering",
                
                "core_positioning_elements": {
                    "target_audience": "Who we serve",
                    "customer_problem": "What problem we solve",
                    "our_solution": "How we solve it",
                    "unique_differentiation": "Why we're different",
                    "proof_points": "Evidence it works",
                },
                
                "dont_list": [
                    "Don't claim we're cheaper than premium brands",
                    "Don't present as 'for everyone'",
                    "Don't emphasize features over benefits",
                    "Don't dilute message across too many angles",
                ],
                
                "messaging_framework": {
                    "emotional_hook": "For the heart",
                    "rational_argument": "For the mind",
                    "social_proof": "From peers",
                    "call_to_action": "Next step",
                },
                
                "tone_and_voice": [
                    "Motivational but realistic",
                    "Expert but accessible",
                    "Professional but friendly",
                    "Inspiring but not preachy",
                ],
            }
        }


def get_brand_positioning(brand_name: str = None) -> BrandPositioning:
    """Factory function for brand positioning."""
    return BrandPositioning(brand_name)
